// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("IfSharp")>]
[<assembly: AssemblyProductAttribute("IfSharp")>]
[<assembly: AssemblyDescriptionAttribute("F# kernel for Jupyter Notebooks.")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "IfSharp"
    let [<Literal>] AssemblyProduct = "IfSharp"
    let [<Literal>] AssemblyDescription = "F# kernel for Jupyter Notebooks."
