// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("IfSharp.Kernel")>]
[<assembly: AssemblyProductAttribute("IfSharp.Kernel")>]
[<assembly: AssemblyDescriptionAttribute("A short summary of your project.")>]
[<assembly: AssemblyVersionAttribute("2.0.2")>]
[<assembly: AssemblyFileVersionAttribute("2.0.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "IfSharp.Kernel"
    let [<Literal>] AssemblyProduct = "IfSharp.Kernel"
    let [<Literal>] AssemblyDescription = "A short summary of your project."
    let [<Literal>] AssemblyVersion = "2.0.2"
    let [<Literal>] AssemblyFileVersion = "2.0.2"
